import { useEffect, useState } from "react";
import { feedbackApi } from "../../services/api";
import { useToast } from "../../contexts/ToastContext";
import { useAuth } from "../../contexts/AuthContext";

export default function Feedback(){
 const {toast}=useToast(); const {user}=useAuth(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [draft,setDraft]=useState({}); const [filter,setFilter]=useState('all');
 const load=()=>feedbackApi.getAll().then(setRows).catch(e=>toast(e.message||'Failed to load feedback','error')).finally(()=>setLoading(false)); useEffect(()=>{load()},[]);
 async function reply(id){const text=(draft[id]||'').trim();if(!text)return toast('Write a reply first.','warning');try{await feedbackApi.reply(id,text);toast('Reply saved.','success');setDraft(d=>({...d,[id]:''}));await load()}catch(e){toast(e.message||'Could not save reply','error')}}
 const visible=rows.filter(r=>filter==='all'||(filter==='unreplied'?!r.staff_reply:!!r.staff_reply)); const avg=rows.length?rows.reduce((s,r)=>s+Number(r.rating||0),0)/rows.length:0;
 return <div className="max-w-6xl mx-auto animate-fade-in"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-7"><div><h1 className="text-2xl font-semibold">Client Feedback</h1><p className="text-sm text-gray-500 mt-1">Owner and staff can review feedback and send a studio reply.</p></div><div className="flex gap-2"><select value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-xl px-3 py-2 text-sm"><option value="all">All Feedback</option><option value="unreplied">Needs Reply</option><option value="replied">Replied</option></select></div></div>
 <div className="grid sm:grid-cols-3 gap-4 mb-6"><div className="bg-white border rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Total Feedback</p><p className="text-3xl font-semibold mt-2">{rows.length}</p></div><div className="bg-white border rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Average Rating</p><p className="text-3xl font-semibold mt-2">{avg.toFixed(1)} <span className="text-amber-400 text-xl">★</span></p></div><div className="bg-white border rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-gray-500">Needs Reply</p><p className="text-3xl font-semibold mt-2">{rows.filter(r=>!r.staff_reply).length}</p></div></div>
 {loading?<div className="text-center text-gray-400 py-10">Loading feedback…</div>:visible.length===0?<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">No feedback in this view.</div>:<div className="space-y-4">{visible.map(f=><article key={f.id} className="bg-white border rounded-2xl p-5 card-shadow"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3"><div><p className="font-semibold text-gray-900">{f.client?.name||'Client'}</p><p className="text-xs text-gray-400 mt-1">{f.appointment?.tracking_number||'General Studio Feedback'} · {new Date(f.created_at).toLocaleDateString('en-PH')}</p></div><div className="text-amber-400">{'★'.repeat(f.rating||0)}<span className="text-gray-200">{'★'.repeat(5-(f.rating||0))}</span></div></div>{f.comment&&<p className="text-sm text-gray-600 mt-4 whitespace-pre-line">{f.comment}</p>}
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4 text-xs">{[['Booking',f.booking_experience],['Staff',f.staff_service],['Studio',f.studio_experience],['Cleanliness',f.cleanliness]].map(([l,v])=><div key={l} className="bg-gray-50 rounded-lg p-2"><span className="text-gray-500">{l}</span><span className="float-right text-amber-500">{v||'—'}★</span></div>)}</div>
 {f.staff_reply?<div className="mt-4 bg-emerald-50 border border-emerald-100 rounded-xl p-4"><p className="text-xs font-semibold text-emerald-800">STUDIO REPLY</p><p className="text-sm text-emerald-900 mt-1 whitespace-pre-line">{f.staff_reply}</p></div>:<div className="mt-4"><label className="text-xs uppercase tracking-wider text-gray-500 block mb-2">Reply as {user?.role==='admin'?'Owner':'Staff'}</label><div className="flex flex-col sm:flex-row gap-2"><textarea value={draft[f.id]||''} onChange={e=>setDraft({...draft,[f.id]:e.target.value})} rows={2} placeholder="Write a courteous response…" className="flex-1 border rounded-xl px-3 py-2 text-sm resize-none"/><button onClick={()=>reply(f.id)} className="bg-gray-900 text-white rounded-xl px-4 py-2 text-sm font-semibold">Send Reply</button></div></div>}</article>)}</div>}
 </div>
}
